const express = require("express")
const router = express.Router()
const expressJoi = require('@escook/express-joi')
const artCate_handler = require('../router_handler/artcate')
const {add_cate_schema} = require("../schema/artcate")
const {delete_cate_schema} = require('../schema/artcate')
const {get_cateByid_schema} = require('../schema/artcate')
const {update_cateByid_schema} = require('../schema/artcate')
router.get('/cates', artCate_handler.getArticleCates)
router.post('/addcates',expressJoi(add_cate_schema),artCate_handler.addArticleCates)
router.post('/deletecate/:id',expressJoi(delete_cate_schema),artCate_handler.deleteCateByid)
router.get('/cates/:id',expressJoi(get_cateByid_schema),artCate_handler.getArticleByid)
router.post('/updatecate',expressJoi(update_cateByid_schema),artCate_handler.UpdateArticleByid)
module.exports = router